### ISSUE TITLE
Store icon sucks

### ISSUE THREAD

**Issue by alecbakholdin** [alecbakholdin/rutgers-ultimate-pockethost#5]
Go to https://rutgersultimate.com, if the store is enabled for you you'll notice that the store icon sucks really bad. Would like it to match the rest of the aesthetic.

Bonus: if you want to make the front page look nicer somehow, please don't stop yourself :)

**Comment by snicub** [comment]
let me cook

**Comment by snicub** [comment]
somewhat done?? still working on design
