### ISSUE TITLE
Images don't have static size when visiting a product with gallery images

### ISSUE THREAD

**Issue by alecbakholdin** [alecbakholdin/rutgers-ultimate-pockethost#6]
Go to https://www.rutgersultimate.com/store/product/r-ultimate-athletic-longsleeve. Reload the page without cache using shift + command + r (or shift + ctrl + r on windows). You'll notice that while the images along the bottom (gallery images) are loading, they are only the size of the spinner, so when the image finally loads, they expand in size and it looks bad. The images should have static dimensions in the gallery, and if not, setting static dimensions will be a viable solution here.

On Chrome, and pretty sure on all major browsers, you can open dev tools and throttle your requests to make the problem more obvious: https://www.google.com/search?q=how+to+throttle+requests+chrome+devtools&rlz=1C5GCEM_enUS1109US1109&oq=how+to+throttle+requests+chrome+devtools&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORigATIHCAEQIRifBdIBCDM4NDBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

Also, please make it so that if there is only one image, like for the beanie: https://www.rutgersultimate.com/store/product/r-ultimate-beanie, there is no gallery. No point in showing pointless clutter.

**Comment by snicub** [comment]
done,

https://github.com/alecbakholdin/rutgers-ultimate-pockethost/pull/8
