### ISSUE TITLE
Add the option for student/team prices to apply to the whole store page

### ISSUE THREAD

**Issue by alecbakholdin** [alecbakholdin/rutgers-ultimate-pockethost#7]
I would like to make it easier for people on the store page to see discounted prices. The current workaround is to go into the cart, apply the discount code, then back out and see the discounted prices. I want this to be possible from the store page because that's like the most common question I get.

Also, would be cool to strike out the higher price and show the sale price to the side like you would see on amazon or something. Will probably implement a discount table in pockethost at some point.

**Comment by snicub** [comment]
I"m strugglign to understand though, shouldn't those only wit the discount code be able to see sale prices? 

Like how would we know to show the discount prices from the get go? My understanding here is that you want currentl players to only have teh discount? 

unless we have a prompt when anyone logs in that first asks for a "Discount COde", then we can apply to the entire store page

**Comment by snicub** [comment]
![Screenshot 2024-11-17 at 15 54 14](https://github.com/user-attachments/assets/c9adb6fe-7831-4687-b795-f17229a084af)
Like I can do this, but this only applies after i've added the disocount code in the cart, you know what i'm sauying/?

**Comment by snicub** [comment]
![Screenshot 2024-11-17 at 15 57 49](https://github.com/user-attachments/assets/f29684df-6def-45ec-a2d4-a15aff4498a0)
here are the correct values, i just noticed they're duped in the prev

**Comment by snicub** [comment]
This issue is also finished, jsut need to discuss how we are approachign the discoun code

**Comment by snicub** [comment]
![Screenshot 2024-11-17 at 16 02 57](https://github.com/user-attachments/assets/e71a779c-095f-4ecd-9309-ae7e9c77a34f)
